package output

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"

	"github.com/netdefense-io/NDCLI/internal/models"
)

// E2E contract test for NDCLI-go#27: the exact JSON body produced by
// NDManager's Pydantic model (build_sync_payload + SyncErrorDetail) must
// decode into models.SyncApplyResponse and render with per-snippet lines.
//
// The wire bytes below were generated by running the NDManager response
// model with the feature branch checked out:
//
//   python3 -c "from schemas.responses import SyncErrorDetail, SyncTriggerResponse; ..."
//
// Keep this as a pinned integration contract — if NDManager changes the
// field name or shape, this test fails and forces an update in lockstep.
const ndmanagerWireJSON = `{
  "message": "Sync triggered for 0 device(s); 1 error(s)",
  "devices_affected": 0,
  "skipped": 0,
  "errors": [
    {
      "device_name": "murphy01",
      "error": "Undefined variables in snippet content",
      "code": "UNDEFINED_VARIABLES",
      "undefined_variables": ["interface_name", "vlan_id"],
      "undefined_variables_by_snippet": {
        "wan-rules":  ["interface_name"],
        "vlan-setup": ["vlan_id"]
      }
    }
  ]
}`

func TestE2E_NDManagerWire_RendersPerSnippetLines(t *testing.T) {
	var resp models.SyncApplyResponse
	if err := json.Unmarshal([]byte(ndmanagerWireJSON), &resp); err != nil {
		t.Fatalf("decode failed: %v", err)
	}
	if len(resp.Errors) != 1 {
		t.Fatalf("expected 1 error, got %d", len(resp.Errors))
	}
	e := resp.Errors[0]
	if e.UndefinedVariablesBySnippet["wan-rules"][0] != "interface_name" {
		t.Errorf("field decoded incorrectly: %+v", e.UndefinedVariablesBySnippet)
	}

	// Run the real formatter path (the one the user sees on the terminal).
	var buf bytes.Buffer
	f := &SimpleFormatter{BaseFormatter: BaseFormatter{Writer: &buf}}
	if err := f.FormatSyncApply(&resp); err != nil {
		t.Fatalf("format: %v", err)
	}
	out := buf.String()
	for _, want := range []string{
		`Snippet "vlan-setup": ${vlan_id}`,
		`Snippet "wan-rules": ${interface_name}`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in rendered output:\n%s", want, out)
		}
	}
	t.Logf("rendered output:\n%s", out)
}

// Backward compat: older NDManager emits only the flat list.
func TestE2E_OldNDManagerWire_FallsBackToFlatList(t *testing.T) {
	const oldWire = `{
      "message": "Sync triggered for 0 device(s); 1 error(s)",
      "devices_affected": 0,
      "skipped": 0,
      "errors": [{
        "device_name": "murphy01",
        "error": "Undefined variables in snippet content",
        "code": "UNDEFINED_VARIABLES",
        "undefined_variables": ["not_a_variable"]
      }]
    }`
	var resp models.SyncApplyResponse
	if err := json.Unmarshal([]byte(oldWire), &resp); err != nil {
		t.Fatalf("decode failed: %v", err)
	}
	var buf bytes.Buffer
	f := &SimpleFormatter{BaseFormatter: BaseFormatter{Writer: &buf}}
	if err := f.FormatSyncApply(&resp); err != nil {
		t.Fatalf("format: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "Undefined: ${not_a_variable}") {
		t.Errorf("expected flat fallback line, got:\n%s", out)
	}
	if strings.Contains(out, `Snippet "`) {
		t.Errorf("unexpected per-snippet line when old wire had no grouping:\n%s", out)
	}
}
